### ISSUE TITLE
anim-bluespheres.pbrt

### ISSUE THREAD

**Issue by wahn** [wahn/rs_pbrt#118]
Compare C++ vs. Rust render times (on **purism** laptop) :

```shell
$ time ~/builds/pbrt/release/pbrt anim-bluespheres.pbrt
pbrt version 3 (built Apr  1 2019 at 17:45:44) [Detected 4 cores]
Copyright (c)1998-2018 Matt Pharr, Greg Humphreys, and Wenzel Jakob.
The source code to pbrt (but *not* the book contents) is covered by the BSD License.
See the file LICENSE.txt for the conditions of the license.
Rendering: [++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++]  (897.6s)
Statistics:
...
real    14m58.087s
user    52m55.853s
sys     0m0.932s
```

So, the C++ implementation needs about **15 minutes** on a 4 processor Linux laptop.

**Comment by wahn** [comment]
```shell
$ time ~/git/self_hosted/Rust/pbrt/target/release/rs_pbrt -i anim-bluespheres.pbrt
pbrt version 0.7.1 [Detected 4 cores]
Copyright (c) 2016-2019 Jan Douglas Bert Walter.
Rust code based on C++ code by Matt Pharr, Greg Humphreys, and Wenzel Jakob.
Film "image"
  "string filename" ["anim-bluespheres.exr"]
  "integer xresolution" [800]
  "integer yresolution" [400]
Sampler "sobol"
  "integer pixelsamples" [1024]
Integrator "path"
Rendering with 4 thread(s) ...
1250 / 1250 [=========================================================================] 100.00 % 0.87/s
Writing image "pbrt.png" with bounds Bounds2 { p_min: Point2 { x: 0, y: 0 }, p_max: Point2 { x: 800, y: 400 } }
Writing image "pbrt_rust.exr" with bounds Bounds2 { p_min: Point2 { x: 0, y: 0 }, p_max: Point2 { x: 800, y: 400 } }

real    24m7.235s
user    83m40.080s
sys     0m4.741s
```

So, the Rust implementation needs more than **24 minutes** on a 4 processor Linux laptop.

**Comment by wahn** [comment]
@matklad suggested to use [heaptrack](https://github.com/KDE/heaptrack) ...

**Comment by wahn** [comment]
Here the difference between the **C++** code:

![heaptrack pbrt](https://user-images.githubusercontent.com/1074865/66457060-5334a180-ea67-11e9-9681-5ef7d2b33216.png)

And the **Rust** counterpart:

![heaptrack rs_pbrt](https://user-images.githubusercontent.com/1074865/66457048-4d3ec080-ea67-11e9-8079-db93e93da994.png)

**Comment by matklad** [comment]
I wonder why allocations at all are happening in the rendering loop? It seems like only scene construction should allocate. I *think* this is orthogonal to arenas: if you don't allocate, you don't need an arena either

**Comment by wahn** [comment]
I started to describe the problem here:

https://www.rs-pbrt.org/blog/arena-based-allocation/

**Comment by wahn** [comment]
And on the user forum:

https://users.rust-lang.org/t/memory-management-which-arena-based-allocation-to-use/33423

**Comment by wahn** [comment]
Instead of implementing `MemoryArena` I tried to replace dynamic dispatch with an `enum` for two **traits**:

1. [Fresnel trait](https://www.rs-pbrt.org/doc/crates/pbrt/core/reflection/trait.Fresnel.html) -> [Fresnel enum](https://www.janwalter.org/doc/rust/pbrt/core/reflection/enum.Fresnel.html)
2. [Bxdf trait](https://www.rs-pbrt.org/doc/crates/pbrt/core/reflection/trait.Bxdf.html) -> [Bxdf enum](https://www.janwalter.org/doc/rust/pbrt/core/reflection/enum.Bxdf.html)

This did not really improve performance, but it might still be worth to try to do this for other traits ...

**Comment by matklad** [comment]
did this actually reduced he number of allocations? Obviously it should have, but it”s always helpful to double check

**Comment by wahn** [comment]
```sh
$ more heaptrack_enum.txt 
heaptrack stats:
        allocations:            259771340
        leaked allocations:     15
        temporary allocations:  76797682

$ more heaptrack_trait.txt 
heaptrack stats:
        allocations:            265922570
        leaked allocations:     200
        temporary allocations:  77808309
```

**Comment by matklad** [comment]
So looks like those traits were by far not the most large source of allocations?

**Comment by wahn** [comment]
I think a big junk of allocation will go to [SurfaceInteraction](https://www.rs-pbrt.org/doc/crates/pbrt/core/interaction/struct.SurfaceInteraction.html) because this is dynamically created during rendering when you hit a shape/geometry and used for shading ...

**Comment by matklad** [comment]
Aha, so I think this is the main problem: https://github.com/wahn/rs_pbrt/blob/c41acd8ed67bc9c300409a48584d2438ac6acdbf/src/shapes/triangle.rs#L339

**Comment by matklad** [comment]
So, what C++ version does it it pre-allocates all the shapes:

https://github.com/mmp/pbrt-v3/blob/9adaee88487772059b65bc322fb2b03ad033d9fc/src/shapes/triangle.cpp#L106-L108

This allows it to store a raw pointer in the Intersection. I think directly translating that to Rust should change `shape: Option<Arc<dyn Shape + Send + Sync>>` to `shape: Option<&'a dyn Shape + Send + Sync>`. This adds a lifetime, but presumably, because the C++ code works, the lifetimes should actually work out

**Comment by wahn** [comment]
After commit 6db4daca6c28c8df3e36d98d7d6c167fd21b2167 the render time went down to **21m36s**. Still too long ...

**Comment by wahn** [comment]
Commit e7bc14b9ce5774229d8e0bbbc9d08629e278bfe4 fixes a bug which effects the acceleration structures (like the BVH). But the render time is still **22m37s**. It is more likely to show effect in scenes with heavy geometry. Let's run such a test on another machine (with more threads) ...

**Comment by wahn** [comment]
This is a long term project and has nothing to do with the `anim-bluespheres.pbrt` test scene. Closing for now ...
