### ISSUE TITLE
Statistics and Profiling from PBRT.

### ISSUE THREAD

**Issue by bsavery** [wahn/rs_pbrt#131]
Hi Jan.  

Was wondering if you had thought about adding the statistics and profiling system from PBRT (the C++ version)?  My thought was to implement them using https://github.com/llogiq/flame and https://docs.rs/counters/0.5.0/counters/ Unless you had other thoughts before I took a stab at it?

**Comment by wahn** [comment]
Hi Brian,

no, so far I haven't dealt with statistics. I do profile entirely with tools like [heaptrack](https://www.rs-pbrt.org/tags/heaptrack/) and [perf](https://www.rs-pbrt.org/tags/perf/). Here are a couple of posts related to [performance](https://www.rs-pbrt.org/tags/performance/) etc. I also use [hotspot](https://github.com/KDAB/hotspot) a GUI for perf on Linux. Let me know if you plan to add similar statistics to the Rust version (as the C++ version outputs).

**Comment by bsavery** [comment]
Yeah after thinking about it more, using those built in tools is probably good enough!
