### ISSUE TITLE
Move rs_pbrt to a proper binary

### ISSUE THREAD

**Issue by abusch** [wahn/rs_pbrt#73]
At the moment the CLI `rs_pbrt` is under `examples`, but as it's the main interface I think it should be a proper binary and be moved under `src/bin/rs_pbrt.rs`. This way it can be invoked by simply doing `cargo run` which most users would expect.

**Comment by wahn** [comment]
OK. I'm not sure how to do this in `Cargo.toml`, and if it has an effect on the CI with Travis, but lets do it. Go ahead if you know what has to be done ... I will update the `Makefile` if neccessary.
