### ISSUE TITLE
Figure out why code gets recompiled even when nothing has changed

### ISSUE THREAD

**Issue by abusch** [wahn/rs_pbrt#81]
When running `cargo build` twice in a row, the second time shouldn't do anything but at the moment it rebuilds anyway, which is pretty annoying. I think I have an idea what's causing it because I ran into it with rustracer (a bug in the version of skeptic used by ply-rs IIRC).

**Comment by abusch** [comment]
This was fixed by bumping the version of skeptic.

**Comment by wahn** [comment]
Thanks. That was really useful and saves a lot of development (compiling) time.
