### ISSUE TITLE
Use generics instead of dynamic dispatch

### ISSUE THREAD

**Issue by fu5ha** [wahn/rs_pbrt#83]
In many places currently, the code uses dynamic dispatch when you could instead use generics and static dispatch. For example, the [render method](https://github.com/wahn/rs_pbrt/blob/master/src/integrators/mod.rs#L78)

```rust
pub fn render(
    scene: &Scene,
    camera: &Arc<Camera + Send + Sync>,
    sampler: &mut Box<Sampler + Send + Sync>,
    integrator: &mut Box<SamplerIntegrator + Send + Sync>,
    num_threads: u8,
) {
```
could instead be
```rust
pub fn render<SC, SA, I> (
    scene: &SC,
    camera: &Arc<Camera + Send + Sync>,
    sampler: &mut SA,
    integrator: &mut I,
    num_threads: u8,
) 
where
    SC: Scene + Send + Sync,
    SA: SamplerIntegrater + Send + Sync,
    I: Integrator + Send + Sync
{
    //....
}
```

**Comment by wahn** [comment]
Thanks for the suggestion. I will look into it ...

**Comment by abusch** [comment]
This is usually not possible because the concrete type of most of the arguments, such as the Integrator, isn't known at compile time. It is only known at runtime after parsing the scene file...

**Comment by wahn** [comment]
I was able to use a generic function in commit 68580a9995ed73f4dd09559e1eb90c11e7dba06d, there might be other places where this makes sense to change ... Thanks (again) for the suggestion.
